language: node_js

node_js:
  - '10'
  - '11'
  - '12'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      node_js: '12'
      script: yarn lint
    - stage: test
      script: yarn test
    - stage: deploy
      node_js: '12'
      script: yarn build
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm whoami
      deploy:
        provider: script
        script: yarn release! --yes
        skip_cleanup: true
        on:
          tags: true
